
# impact_bpr.py — Member B exposes this for Member C twin
# Generated by PARKLENS Member B notebook

ALPHA = 3.59
BETA  = 0.40
SAT_FLOW = 1800
VOT_RS_PER_MIN = 3.0

ROAD_CLASS_DEFAULTS = {
    "motorway":  {"lanes": 3, "v0_kmh": 80},
    "arterial":  {"lanes": 2, "v0_kmh": 50},
    "collector": {"lanes": 2, "v0_kmh": 40},
    "local":     {"lanes": 1, "v0_kmh": 30},
    "unknown":   {"lanes": 2, "v0_kmh": 40},
}

_segment_registry = {}   # loaded from hotspots_enriched.csv at startup

def load_segments(hotspots_enriched_path):
    """Call once at startup to populate segment registry."""
    import pandas as pd
    global _segment_registry
    df = pd.read_csv(hotspots_enriched_path)
    for _, row in df.iterrows():
        rc   = row.get("road_class", "unknown")
        info = ROAD_CLASS_DEFAULTS.get(rc, ROAD_CLASS_DEFAULTS["unknown"])
        _segment_registry[row["h3_cell"]] = {
            "lanes":       row.get("lanes", info["lanes"]),
            "v0_kmh":      row.get("v0_kmh", info["v0_kmh"]),
            "V_calibrated": row.get("V_calibrated", 0.3 * info["lanes"] * SAT_FLOW),
            "road_class":  rc,
        }

def recompute(segment_id: str, c_io: float) -> dict:
    """
    Recompute BPR delay for a segment with given C_io (capacity removed).
    Returns: {T_a_with, T_a_without, delay_ratio, veh_min_lost, rupees_lost}
    """
    seg = _segment_registry.get(segment_id, {})
    lanes  = seg.get("lanes", 2)
    v0_kmh = seg.get("v0_kmh", 40)
    V      = seg.get("V_calibrated", 0.3 * lanes * SAT_FLOW)
    C      = lanes * SAT_FLOW

    C_eff = max(C - c_io, 0.1 * C)
    seg_km = 0.5
    T_0    = (seg_km / v0_kmh) * 60

    T_a    = T_0 * (1 + ALPHA * (V / C_eff) ** BETA)
    T_a_without = T_0 * (1 + ALPHA * (V / C)    ** BETA)

    delay_ratio   = T_a / T_a_without if T_a_without > 0 else 1.0
    delay_per_veh = T_a - T_a_without
    veh_min_lost  = delay_per_veh * V * 8   # 8h window
    rupees_lost   = veh_min_lost * VOT_RS_PER_MIN

    return {
        "T_a_with":     round(T_a, 4),
        "T_a_without":  round(T_a_without, 4),
        "delay_ratio":  round(delay_ratio, 4),
        "veh_min_lost": round(veh_min_lost, 1),
        "rupees_lost":  round(rupees_lost, 0),
    }
